const CREATE_USER = 'CREATE_USER'
const LOGIN = 'LOGIN'
const USER_ERROR = 'USER_ERROR'
const GET_ITEMS = 'GET_ITEMS'
const GET_ALL_ITEMS = 'GET_ALL_ITEMS'
const SELECT_ITEM = 'SELECT_ITEM'
const CHANGE_QUANTITY = 'CHANGE_QUANTITY'
const INCREMENT_CURR_ITEM_IDX = 'INCREMENT_CURR_ITEM_IDX'
const PLACE_ORDER = 'PLACE_ORDER'
const SET_PRICE = 'SET_PRICE'
const GET_ALL_ORDERS = 'GET_ALL_ORDERS'

export {
    CREATE_USER,
    LOGIN,
    USER_ERROR,
    GET_ALL_ITEMS,
    SELECT_ITEM,
    CHANGE_QUANTITY,
    INCREMENT_CURR_ITEM_IDX,
    PLACE_ORDER,
    SET_PRICE,
    GET_ALL_ORDERS
}