const CREATE_USER = 'CREATE_USER'
const LOGIN = 'LOGIN'
const USER_ERROR = 'USER_ERROR'
const GET_ITEMS = 'GET_ITEMS'
const GET_ALL_ITEMS = 'GET_ALL_ITEMS'
const SELECT_ITEM = 'SELECT_ITEM'

export {
    CREATE_USER,
    LOGIN,
    USER_ERROR,
    GET_ALL_ITEMS,
    SELECT_ITEM
}